### ISSUE TITLE
velero snapshots not deleted after expired velero backups are deleted.

### ISSUE THREAD

**Issue by JuanGarcia01** [Lirt/velero-plugin-for-openstack#60] opened 2023-03-30 14:28 UTC
**what is happening ?**
velero snapshots not deleted after expired velero backups are deleted.

**what is expected ?**
after TTL for velero backups has expired velero backups will get deleted and all associated velero snapshots will get deleted.

**Details:**
we have a velero backup schedule that runs creates a backup every 15 minutes. Each of these velero backups has a TTL of only 02 hours. After the velero backup has expired the backup will of into a "deleting" state and eventually the velero backup gets deleted. The problem we are seeing is. that the associated velero snapshots are not getting deleted.  This then creates a large amount of orphaned snapshots that are associated with velero  backups that longer exist.

**Comment by Lirt** [comment] 2023-03-30 17:22
Hello @JuanGarcia01, 

Thank you for report. I will look into this issue next week (after my vacation).

**Comment by JuanGarcia01** [comment] 2023-03-30 17:26
Additional Notes:

we have a production environment running in Openstack converged cloud landscape.

we are running backups of our production environment using the velero-plugin-for-openstack solution
https://github.com/Lirt/velero-plugin-for-openstack

we have a velero backup schedule that creates a backup of this environment every 15 minutes
the TTL on these backups is only 02 hours. 

when a velero backup is successfully created it creates 07 velero snapshots in the converged cloud project
the snapshot range in size as follows 500Gb x 1 , 150Gb x 2 , 30G x 1 , and 10Gb x 3  = 880 Gb

ISSUE:
when the velero backup TTL has expired - the backup will go into a deletion state. When the backup is deleted by the k8s cluster the associated snapshots are not getting deleted. 

What is expected to happen?
After 02 hours the expired velero backup should delete and all associated snapshots should get deleted as well.
Currently this is not happening.

Additional notes
- when a new velero backup is created... 07 snapshots are created. Some of the larger snapshots will remain in a "creating" state for up to 30 minutes before they are in an "available" state.
- Sometimes It can take an expired velero backup up to one hour before it is deleted 
- We have the same  velero-plugin-for-openstack solution running in another project
In this project the velero backup schedule creates one backup every 24 hrs. The velero backup creates 07 snapshots.
The TTL for these backups is 05 days which is much longer. There are no issues with snapshots getting automatically when the velero backup is deleted.

**Comment by JuanGarcia01** [comment] 2023-04-03 14:41
Hello @Lirt 
Will you be able to look at this issue soon ?
The issue is somewhat of a high urgency because it is impacting the availability of our production backups.

**Comment by Lirt** [comment] 2023-04-05 16:17
Hi,

It would be helpful if you checked velero logs for any hint regarding this. There can be message about snapshot failing, timeouts or similar things. 

I will try to replicate this scenario, but I can't give you estimate as there are Easter holidays and other pending work from my side.

**Comment by Lirt** [comment] 2023-05-09 09:13
Hi again,

I'm using Velero 1.11 for tests. I'm trying to have a schedule with small TTL duration as you mentioned. In my case I see that backup expired 30 minutes ago, but it's not removed.

In [Velero 1.9 documentation](https://velero.io/docs/v1.9/how-velero-works/#set-a-backup-to-expire) I found this:

> The effects of expiration are not applied immediately, they are applied when the gc-controller runs its reconciliation loop every hour. 
> If backup fails to delete, a label velero.io/gc-failure=<Reason> will be added to the backup custom resource.

In Velero newer than 1.9 the line about `gc-controller` is not present anymore (they refactored the controller to kubebuilder) but anyway the backup is not removed immediately.

However I don't see any issue with deleting snapshots. Here the best would be if you provide velero logs and description of backups which should have `velero.io/gc-failure=<Reason>`. I think the backup cannot be deleted without deleting snapshot. I see that when snapshot is not possible to be deleted, backup stays in `Deleting` state.

Also notice that snapshots have identical names, but different IDs. You need to do `openstack volume snapshot show <ID>` and see what is inside `properties.velero.io/backup=` to find out from which backup is the snapshot created.

**Comment by Lirt** [comment] 2023-05-19 09:16
According to question why is backup not deleted right after TTL expires, it is caused by Velero running reconciliation every 60 minutes and can be changed by flag `--garbage-collection-frequency duration`. (see discussion https://github.com/vmware-tanzu/velero/issues/6245#issue-1701744138).

Regarding rest as no more logs or answers were provided I am closing this issue.

**Closed by Lirt** 2023-05-19 09:16 UTC
